# Numpy Test


In [1]:
import numpy as np
data = np.random.rand(3,5,1)

print(data)
print('data shape',data.shape)

[[[0.48210123]
  [0.48528944]
  [0.8168223 ]
  [0.32080142]
  [0.60639619]]

 [[0.74834432]
  [0.31833445]
  [0.69924429]
  [0.18148809]
  [0.00438397]]

 [[0.19582534]
  [0.99634782]
  [0.70457388]
  [0.27739078]
  [0.3625465 ]]]
data shape (3, 5, 1)


In [2]:
data2 = data[0:2]
print(data2)
print('data2 shape',data2.shape)

[[[0.48210123]
  [0.48528944]
  [0.8168223 ]
  [0.32080142]
  [0.60639619]]

 [[0.74834432]
  [0.31833445]
  [0.69924429]
  [0.18148809]
  [0.00438397]]]
data2 shape (2, 5, 1)


In [6]:

x = data[:2,:-1,:]
print('x shape',x.shape)
print(x)


y = data[:2,-1,:]
print('y shape',y.shape)
print(y)

x shape (2, 4, 1)
[[[0.48210123]
  [0.48528944]
  [0.8168223 ]
  [0.32080142]]

 [[0.74834432]
  [0.31833445]
  [0.69924429]
  [0.18148809]]]
y shape (2, 1)
[[0.60639619]
 [0.00438397]]
